pipeline {
    agent any

    options {
    //     buildDiscarder(logRotator(numToKeepStr: '10')) // Keep only the last 10 build logs
         timeout(time: 1, unit: 'HOURS') // Set a timeout of 1 hour for the entire pipeline
    //     disableConcurrentBuilds() // Disable concurrent builds of this pipeline
    //     skipDefaultCheckout() // Skip the default checkout step, useful if you want to manually manage the repository checkout
    //     quietPeriod(5) // Set a quiet period of 5 seconds before starting a build after a new commit is detected
    //     retry(3) // Retry the entire pipeline up to 3 times if it fails
    buildDiscarder(logRotator(numToKeepStr: '5'))//discard old builds to save disk space
    }

    triggers {
        githubPush()
    }

    environment {
        DOCKER_HUB_USERNAME="devopseasylearning"
        ALPHA_APPLICATION_01_REPO="alpha-application-01"
        ALPHA_APPLICATION_02_REPO="alpha-application-02"
        DOCKER_CREDENTIAL_ID = 's8-test-docker-hub-auth'
    }

    parameters {
        string(name: 'BRANCH_NAME', defaultValue: 's8lagataf02', description: '')
        string(name: 'APP1_TAG', defaultValue: 'latest', description: '')
        string(name: 'APP2_TAG', defaultValue: 'latest', description: '')
        string(name: 'PORT_ON_DOCKER_HOST', defaultValue: '', description: '')
    }

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    git credentialsId: 'jenkins-ssh-agents-private-key',
                        url: 'git@github.com:DEL-ORG/s8-web-2.git',
                        branch: "${params.BRANCH_NAME}"
                }
            }
        }
        stage('Test Timeout') {
            steps {
                script {
                    sleep 5
                }
            }
        }
    }
}
